# Generated by Django 4.0.6 on 2022-07-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='Competence',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='Enseignant',
        ),
    ]
