# Generated by Django 4.0.6 on 2022-07-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0003_rename_position_competence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnseignantCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='position',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='position',
            field=models.ManyToManyField(related_name='persons', through='up.EnseignantCompetence', to='up.competence'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='up.competence')),
            ],
        ),
        migrations.AddField(
            model_name='enseignantcompetence',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.enseignant'),
        ),
        migrations.AddField(
            model_name='enseignantcompetence',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.competence'),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.module')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.enseignant')),
            ],
        ),
    ]
