# Generated by Django 4.0.6 on 2022-07-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0004_enseignantcompetence_remove_enseignant_position_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnseignantCompetence',
            new_name='PersonSkill',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='modules',
            field=models.ManyToManyField(related_name='modules', through='up.Affectation', to='up.module'),
        ),
    ]
