# Generated by Django 4.0.6 on 2022-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0005_rename_enseignantcompetence_personskill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personskill',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
