# Generated by Django 4.0.6 on 2022-07-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0006_alter_affectation_id_alter_personskill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.niveau')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.option')),
            ],
        ),
        migrations.AddField(
            model_name='affectation',
            name='classe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='up.classe'),
        ),
    ]
