# Generated by Django 4.0.6 on 2022-07-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0007_niveau_option_classe_affectation_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='hours',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='name',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='charge_actuelle',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='charge',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='date_debut',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='date_fin',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='niveau',
            name='name',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
