# Generated by Django 4.0.6 on 2022-07-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0008_affectation_hours_classe_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
