# Generated by Django 4.0.6 on 2022-07-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0009_alter_option_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='date_debut',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='date_fin',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
