# Generated by Django 4.0.6 on 2022-07-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0010_alter_module_date_debut_alter_module_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='up.option'),
        ),
    ]
