# Generated by Django 4.0.6 on 2022-07-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0011_alter_classe_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='up.option'),
        ),
    ]
