# Generated by Django 4.0.6 on 2022-07-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0012_alter_classe_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='up.enseignant'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.option'),
        ),
    ]
