# Generated by Django 4.0.6 on 2022-07-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0013_alter_affectation_person_alter_classe_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='niveau',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='up.niveau'),
        ),
        migrations.AddField(
            model_name='module',
            name='option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='up.option'),
        ),
    ]
