# Generated by Django 4.0.6 on 2022-07-30 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0015_alter_affectation_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='up.enseignant'),
        ),
    ]
