# Generated by Django 4.0.6 on 2022-07-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0016_alter_affectation_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='id_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='up.competence'),
        ),
    ]
