# Generated by Django 4.0.6 on 2022-08-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0017_alter_module_id_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='pwd',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='charge_actuelle',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='emp_code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='mobile',
            field=models.CharField(max_length=8),
        ),
    ]
