# Generated by Django 4.0.6 on 2022-08-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0018_enseignant_email_enseignant_pwd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='cin',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
