# Generated by Django 4.0.6 on 2022-08-29 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0019_enseignant_cin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='id_comp',
        ),
        migrations.AddField(
            model_name='module',
            name='skillmodule',
            field=models.ManyToManyField(related_name='moduleskills', through='up.ModuleSkill', to='up.competence'),
        ),
        migrations.AddField(
            model_name='moduleskill',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.module'),
        ),
        migrations.AddField(
            model_name='moduleskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.competence'),
        ),
    ]
