# Generated by Django 4.0.6 on 2022-08-30 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0020_moduleskill_remove_module_id_comp_module_skillmodule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='skillmodule',
        ),
        migrations.AddField(
            model_name='module',
            name='skillmodule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='up.competence'),
        ),
        migrations.DeleteModel(
            name='ModuleSkill',
        ),
    ]
