# Generated by Django 4.0.6 on 2022-08-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0021_remove_module_skillmodule_module_skillmodule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Up',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='enseignant',
            name='up',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='up.up'),
        ),
        migrations.AddField(
            model_name='module',
            name='up',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='up.up'),
        ),
    ]
