# Generated by Django 4.0.6 on 2022-08-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0022_up_enseignant_up_module_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='pwd',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
