# Generated by Django 4.0.6 on 2022-08-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0023_alter_enseignant_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='role',
            field=models.IntegerField(blank=True, choices=[('1', 'Enseignant'), ('2', 'Responsable')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='type_e',
            field=models.IntegerField(blank=True, choices=[('1', 'Permanant'), ('2', 'Vacataire'), ('3', 'Alternant')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='type_r',
            field=models.IntegerField(blank=True, choices=[('1', 'Coordinateur Up'), ('2', 'Cooridnateur projet'), ('3', 'responsable Option'), ('4', 'responsable Stage')], default=None, null=True),
        ),
    ]
