# Generated by Django 4.0.6 on 2022-08-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0024_enseignant_role_enseignant_type_e_enseignant_type_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'Enseignant'), ('2', 'Responsable')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='type_e',
            field=models.CharField(blank=True, choices=[('1', 'Permanant'), ('2', 'Vacataire'), ('3', 'Alternant')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='type_r',
            field=models.CharField(blank=True, choices=[('1', 'Coordinateur Up'), ('2', 'Cooridnateur projet'), ('3', 'responsable Option'), ('4', 'responsable Stage')], default=None, max_length=10, null=True),
        ),
    ]
