# Generated by Django 4.0.6 on 2022-09-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0025_alter_enseignant_role_alter_enseignant_type_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='isactive',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='type_r',
            field=models.CharField(blank=True, choices=[('1', 'Coordinateur Up'), ('2', 'Cooridnateur projet'), ('3', 'Responsable Option'), ('4', 'Responsable Stage')], default=None, max_length=10, null=True),
        ),
    ]
