# Generated by Django 4.0.6 on 2022-09-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0026_classe_isactive_alter_enseignant_type_r'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='isactive',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='isactive',
            field=models.BooleanField(default=0),
        ),
    ]
