# Generated by Django 4.0.6 on 2022-09-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0027_remove_classe_isactive_enseignant_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notify_detail', models.TextField()),
                ('status', models.BooleanField()),
                ('read_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='up.enseignant')),
            ],
        ),
    ]
