# Generated by Django 4.0.6 on 2022-09-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0028_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='charge_maximale',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
