# Generated by Django 4.0.6 on 2022-09-14 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0029_enseignant_charge_maximale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('message', models.CharField(max_length=100000000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='up.enseignant')),
            ],
        ),
    ]
