# Generated by Django 4.0.6 on 2022-09-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0030_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='up',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
