# Generated by Django 4.0.6 on 2022-09-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0032_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='forget_password_token',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
