# Generated by Django 4.0.6 on 2022-09-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0033_enseignant_forget_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='up',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='up.up'),
        ),
    ]
