# Generated by Django 4.0.6 on 2022-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0036_remove_affectation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
