# Generated by Django 4.0.6 on 2022-09-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0037_affectation_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation',
            name='active',
        ),
    ]
