# Generated by Django 4.0.6 on 2022-09-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0039_affectation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='dispo_desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='classe',
            name='is_dispo',
            field=models.BooleanField(default=1),
        ),
    ]
