# Generated by Django 4.0.6 on 2022-09-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0040_classe_dispo_desc_classe_is_dispo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='dispo_desc',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='is_dispo',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='dispo_desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='is_dispo',
            field=models.BooleanField(default=1),
        ),
    ]
