# Generated by Django 4.0.6 on 2022-09-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0041_remove_classe_dispo_desc_remove_classe_is_dispo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('date_debut', models.DateField(blank=True, default=None, null=True)),
                ('date_fin', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='module',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='module',
            name='periode',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='up.periode'),
        ),
    ]
