# Generated by Django 4.0.6 on 2022-09-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0042_periode_remove_module_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='periode_indispo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='up.periode'),
        ),
    ]
