# Generated by Django 4.0.6 on 2022-09-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0043_enseignant_periode_indispo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periode',
            old_name='date_debut',
            new_name='date_debut_1',
        ),
        migrations.RenameField(
            model_name='periode',
            old_name='date_fin',
            new_name='date_debut_2',
        ),
        migrations.AddField(
            model_name='periode',
            name='date_fin_1',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='periode',
            name='date_fin_2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
