# Generated by Django 4.0.6 on 2022-09-27 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0044_rename_date_debut_periode_date_debut_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='semestre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='up.periode'),
        ),
        migrations.AlterField(
            model_name='module',
            name='periode',
            field=models.CharField(blank=True, choices=[('1', 'Periode 1'), ('2', 'Periode 2')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='skillmodule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='up.competence'),
        ),
    ]
