# Generated by Django 4.0.6 on 2022-09-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0045_module_semestre_alter_module_periode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periode',
            old_name='date_debut_1',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='periode',
            old_name='date_fin_2',
            new_name='date_fin',
        ),
        migrations.RenameField(
            model_name='periode',
            old_name='date_debut_2',
            new_name='date_inter',
        ),
        migrations.RemoveField(
            model_name='periode',
            name='date_fin_1',
        ),
    ]
