# Generated by Django 4.0.6 on 2022-09-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0046_rename_date_debut_1_periode_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='periode',
            field=models.CharField(blank=True, choices=[('1', 'Periode 1'), ('2', 'Periode 2')], default=None, max_length=10, null=True),
        ),
    ]
