# Generated by Django 4.0.6 on 2022-09-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0047_enseignant_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='forget_password_token',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
