# Generated by Django 4.0.6 on 2022-09-28 23:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0048_alter_enseignant_forget_password_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee_univ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sem1_year', models.CharField(blank=True, default=datetime.datetime.now, max_length=4)),
                ('sem2_year', models.CharField(blank=True, default=datetime.datetime.now, max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='affectation',
            name='annee_univ',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='up.annee_univ'),
        ),
        migrations.AddField(
            model_name='classe',
            name='annee_univ',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='up.annee_univ'),
        ),
        migrations.AddField(
            model_name='module',
            name='annee_univ',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='up.annee_univ'),
        ),
    ]
