# Generated by Django 4.0.6 on 2022-09-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0049_annee_univ_affectation_annee_univ_classe_annee_univ_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='annee_univ',
        ),
    ]
