# Generated by Django 4.0.6 on 2022-10-04 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0050_remove_module_annee_univ'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='year_indispo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='up.annee_univ'),
        ),
    ]
