# Generated by Django 4.0.6 on 2022-10-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0051_enseignant_year_indispo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='periode',
            field=models.CharField(blank=True, choices=[('1', 'Periode 1'), ('2', 'Periode 2'), ('3', 'Tout')], default=None, max_length=10, null=True),
        ),
    ]
